#!/usr/bin/env bash
# Standalone manifest integrity checks against the real plan model.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BUILD="$(mktemp -d "${TMPDIR:-/tmp}/mixr-manifest-tests.XXXXXX")"
trap 'rm -rf "$BUILD"' EXIT
export CLANG_MODULE_CACHE_PATH="${CLANG_MODULE_CACHE_PATH:-$BUILD/module-cache}"
SOURCES=(
  "$ROOT/Mixr/Models/MixrTimeline.swift"
  "$ROOT/Mixr/Models/ClipEffects.swift"
  "$ROOT/Mixr/Models/MixrTrack.swift"
  "$ROOT/Mixr/Models/SongAnalysis.swift"
  "$ROOT/Mixr/Models/SongSignalAnalysis.swift"
  "$ROOT/Mixr/Models/AutoChorusIsland.swift"
  "$ROOT/Mixr/Models/SoundEffects.swift"
  "$ROOT/Mixr/Models/AutoClubTempo.swift"
  "$ROOT/Mixr/Models/AutoClubPulse.swift"
  "$ROOT/Mixr/Models/AutoClubFlavor.swift"
  "$ROOT/Mixr/Models/AutoCompatibility.swift"
  "$ROOT/Mixr/Models/AutoMashability.swift"
  "$ROOT/Mixr/Models/AutoPivotWord.swift"
  "$ROOT/Mixr/Models/AutoStemSidecar.swift"
  "$ROOT/Mixr/Models/AutoSectionCatalog.swift"
  "$ROOT/Mixr/Models/AutoRemixPlan.swift"
  "$ROOT/Mixr/Models/AutoJoinManifest.swift"
  "$ROOT/Mixr/Models/AutoRemixPlanner.swift"
  "$ROOT/Mixr/Models/AutoJoinEngine.swift"
  "$ROOT/Mixr/Models/AutoRemixValidator.swift"
  "$ROOT/Mixr/Models/AutoRemixApplier.swift"
  "$ROOT/Mixr/Models/AutoRemixRunner.swift"
  "$ROOT/Mixr/Models/AutoArrangementEngine.swift"
  "$ROOT/Mixr/Models/AutoTransitionEnvelope.swift"
  "$ROOT/Mixr/Models/AutoGainPolicy.swift"
  "$ROOT/Mixr/Models/AutoRemixDiagnostics.swift"
  "$ROOT/Mixr/Models/AutoOfflineMixdown.swift"
  "$ROOT/Mixr/Models/AutoListenLoop.swift"
  "$ROOT/Mixr/Models/AutoMasterBus.swift"
  "$ROOT/Mixr/Models/AutoPCMLoader.swift"
  "$ROOT/DevTests/AutoRemixTestStubs.swift"
)

cp "$ROOT/DevTests/AutoJoinManifestIntegrityTests.swift" "$BUILD/main.swift"
xcrun swiftc "${SOURCES[@]}" "$BUILD/main.swift" -o "$BUILD/tests"
"$BUILD/tests"
